"""Tolerant country matching for per-edition story selection.

News sources tag a story's country inconsistently: full names
("United States of America"), short names ("United States"), aliases
("USA", "Britain"), ISO codes ("US"/"USA"), or accented spellings
("Cote d'Ivoire"). Editions declare their ``sourceCountries`` as full
names. This module canonicalizes any of those forms to a single key so
selection can compare them reliably.

The alias table is generated from ISO country data at build time and
embedded below, so the pipeline has no runtime dependency.
"""

from __future__ import annotations

import re
import unicodedata

_ALIAS_TO_CANONICAL = {
    'ae': 'united arab emirates',
    'ago': 'angola',
    'algeria': 'algeria',
    'am': 'armenia',
    'america': 'united states of america',
    'angola': 'angola',
    'ao': 'angola',
    'ar': 'argentina',
    'arab republic of egypt': 'egypt',
    'are': 'united arab emirates',
    'arg': 'argentina',
    'argentina': 'argentina',
    'argentine republic': 'argentina',
    'arm': 'armenia',
    'armenia': 'armenia',
    'at': 'austria',
    'au': 'australia',
    'aus': 'australia',
    'australia': 'australia',
    'austria': 'austria',
    'aut': 'austria',
    'az': 'azerbaijan',
    'aze': 'azerbaijan',
    'azerbaijan': 'azerbaijan',
    'bahrain': 'bahrain',
    'be': 'belgium',
    'bel': 'belgium',
    'belarus': 'belarus',
    'belgium': 'belgium',
    'ben': 'benin',
    'benin': 'benin',
    'bf': 'burkina faso',
    'bfa': 'burkina faso',
    'bh': 'bahrain',
    'bhr': 'bahrain',
    'bj': 'benin',
    'blr': 'belarus',
    'bo': 'bolivia',
    'bol': 'bolivia',
    'bolivia': 'bolivia',
    'bolivia plurinational state of': 'bolivia',
    'br': 'brazil',
    'bra': 'brazil',
    'brazil': 'brazil',
    'britain': 'united kingdom',
    'burkina faso': 'burkina faso',
    'by': 'belarus',
    'ca': 'canada',
    'cabo verde': 'cape verde',
    'cameroon': 'cameroon',
    'can': 'canada',
    'canada': 'canada',
    'cape verde': 'cape verde',
    'cd': 'democratic republic of the congo',
    'ch': 'switzerland',
    'chad': 'chad',
    'che': 'switzerland',
    'chile': 'chile',
    'china': 'china',
    'chl': 'chile',
    'chn': 'china',
    'ci': 'cote d ivoire',
    'civ': 'cote d ivoire',
    'cl': 'chile',
    'cm': 'cameroon',
    'cmr': 'cameroon',
    'cn': 'china',
    'co': 'colombia',
    'cod': 'democratic republic of the congo',
    'col': 'colombia',
    'colombia': 'colombia',
    'congo kinshasa': 'democratic republic of the congo',
    'congo the democratic republic of the': 'democratic republic of the congo',
    'costa rica': 'costa rica',
    'cote d ivoire': 'cote d ivoire',
    'cote divoire': 'cote d ivoire',
    'cpv': 'cape verde',
    'cr': 'costa rica',
    'cri': 'costa rica',
    'cv': 'cape verde',
    'cy': 'cyprus',
    'cyp': 'cyprus',
    'cyprus': 'cyprus',
    'cz': 'czech republic',
    'cze': 'czech republic',
    'czech republic': 'czech republic',
    'czechia': 'czech republic',
    'de': 'germany',
    'democratic republic of sao tome and principe': 'sao tome and principe',
    'democratic republic of the congo': 'democratic republic of the congo',
    'democratic republic of timor leste': 'timor leste',
    'deu': 'germany',
    'do': 'dominican republic',
    'dom': 'dominican republic',
    'dominican republic': 'dominican republic',
    'dr congo': 'democratic republic of the congo',
    'drc': 'democratic republic of the congo',
    'dz': 'algeria',
    'dza': 'algeria',
    'eastern republic of uruguay': 'uruguay',
    'ec': 'ecuador',
    'ecu': 'ecuador',
    'ecuador': 'ecuador',
    'eg': 'egypt',
    'egy': 'egypt',
    'egypt': 'egypt',
    'el salvador': 'el salvador',
    'emirates': 'united arab emirates',
    'england': 'united kingdom',
    'es': 'spain',
    'esp': 'spain',
    'federal republic of germany': 'germany',
    'federative republic of brazil': 'brazil',
    'fr': 'france',
    'fra': 'france',
    'france': 'france',
    'french republic': 'france',
    'gb': 'united kingdom',
    'gbr': 'united kingdom',
    'ge': 'georgia',
    'geo': 'georgia',
    'georgia': 'georgia',
    'germany': 'germany',
    'gnb': 'guinea bissau',
    'grand duchy of luxembourg': 'luxembourg',
    'great britain': 'united kingdom',
    'gt': 'guatemala',
    'gtm': 'guatemala',
    'guatemala': 'guatemala',
    'guinea bissau': 'guinea bissau',
    'gw': 'guinea bissau',
    'hashemite kingdom of jordan': 'jordan',
    'hn': 'honduras',
    'hnd': 'honduras',
    'honduras': 'honduras',
    'il': 'israel',
    'in': 'india',
    'ind': 'india',
    'india': 'india',
    'iq': 'iraq',
    'ir': 'iran',
    'iran': 'iran',
    'iran islamic republic of': 'iran',
    'iraq': 'iraq',
    'irn': 'iran',
    'irq': 'iraq',
    'islamic republic of iran': 'iran',
    'isr': 'israel',
    'israel': 'israel',
    'it': 'italy',
    'ita': 'italy',
    'italian republic': 'italy',
    'italy': 'italy',
    'ivory coast': 'cote d ivoire',
    'japan': 'japan',
    'jo': 'jordan',
    'jor': 'jordan',
    'jordan': 'jordan',
    'jp': 'japan',
    'jpn': 'japan',
    'kaz': 'kazakhstan',
    'kazakhstan': 'kazakhstan',
    'kg': 'kyrgyzstan',
    'kgz': 'kyrgyzstan',
    'kingdom of bahrain': 'bahrain',
    'kingdom of belgium': 'belgium',
    'kingdom of morocco': 'morocco',
    'kingdom of saudi arabia': 'saudi arabia',
    'kingdom of spain': 'spain',
    'kingdom of the netherlands': 'netherlands',
    'kuwait': 'kuwait',
    'kw': 'kuwait',
    'kwt': 'kuwait',
    'kyrgyz republic': 'kyrgyzstan',
    'kyrgyzstan': 'kyrgyzstan',
    'kz': 'kazakhstan',
    'lb': 'lebanon',
    'lbn': 'lebanon',
    'lby': 'libya',
    'lebanese republic': 'lebanon',
    'lebanon': 'lebanon',
    'li': 'liechtenstein',
    'libya': 'libya',
    'lie': 'liechtenstein',
    'liechtenstein': 'liechtenstein',
    'lu': 'luxembourg',
    'lux': 'luxembourg',
    'luxembourg': 'luxembourg',
    'ly': 'libya',
    'ma': 'morocco',
    'mar': 'morocco',
    'md': 'moldova',
    'mda': 'moldova',
    'mex': 'mexico',
    'mexico': 'mexico',
    'moldova': 'moldova',
    'moldova republic of': 'moldova',
    'morocco': 'morocco',
    'moz': 'mozambique',
    'mozambique': 'mozambique',
    'mx': 'mexico',
    'mz': 'mozambique',
    'ne': 'niger',
    'ner': 'niger',
    'netherlands': 'netherlands',
    'new zealand': 'new zealand',
    'ni': 'nicaragua',
    'nic': 'nicaragua',
    'nicaragua': 'nicaragua',
    'niger': 'niger',
    'nl': 'netherlands',
    'nld': 'netherlands',
    'nz': 'new zealand',
    'nzl': 'new zealand',
    'om': 'oman',
    'oman': 'oman',
    'omn': 'oman',
    'pa': 'panama',
    'palestine': 'palestine',
    'palestine state of': 'palestine',
    'pan': 'panama',
    'panama': 'panama',
    'paraguay': 'paraguay',
    'pe': 'peru',
    'people s democratic republic of algeria': 'algeria',
    'people s republic of china': 'china',
    'per': 'peru',
    'peru': 'peru',
    'pl': 'poland',
    'plurinational state of bolivia': 'bolivia',
    'pol': 'poland',
    'poland': 'poland',
    'portugal': 'portugal',
    'portuguese republic': 'portugal',
    'principality of liechtenstein': 'liechtenstein',
    'prt': 'portugal',
    'pry': 'paraguay',
    'ps': 'palestine',
    'pse': 'palestine',
    'pt': 'portugal',
    'py': 'paraguay',
    'qa': 'qatar',
    'qat': 'qatar',
    'qatar': 'qatar',
    'republic of angola': 'angola',
    'republic of armenia': 'armenia',
    'republic of austria': 'austria',
    'republic of azerbaijan': 'azerbaijan',
    'republic of belarus': 'belarus',
    'republic of benin': 'benin',
    'republic of cabo verde': 'cape verde',
    'republic of cameroon': 'cameroon',
    'republic of chad': 'chad',
    'republic of chile': 'chile',
    'republic of colombia': 'colombia',
    'republic of costa rica': 'costa rica',
    'republic of cote d ivoire': 'cote d ivoire',
    'republic of cyprus': 'cyprus',
    'republic of ecuador': 'ecuador',
    'republic of el salvador': 'el salvador',
    'republic of guatemala': 'guatemala',
    'republic of guinea bissau': 'guinea bissau',
    'republic of honduras': 'honduras',
    'republic of india': 'india',
    'republic of iraq': 'iraq',
    'republic of kazakhstan': 'kazakhstan',
    'republic of moldova': 'moldova',
    'republic of mozambique': 'mozambique',
    'republic of nicaragua': 'nicaragua',
    'republic of panama': 'panama',
    'republic of paraguay': 'paraguay',
    'republic of peru': 'peru',
    'republic of poland': 'poland',
    'republic of senegal': 'senegal',
    'republic of tajikistan': 'tajikistan',
    'republic of the niger': 'niger',
    'republic of tunisia': 'tunisia',
    'republic of turkiye': 'turkey',
    'republic of uzbekistan': 'uzbekistan',
    'ru': 'russia',
    'rus': 'russia',
    'russia': 'russia',
    'russian federation': 'russia',
    'sa': 'saudi arabia',
    'sao tome and principe': 'sao tome and principe',
    'sau': 'saudi arabia',
    'saudi arabia': 'saudi arabia',
    'sen': 'senegal',
    'senegal': 'senegal',
    'slv': 'el salvador',
    'sn': 'senegal',
    'spain': 'spain',
    'st': 'sao tome and principe',
    'state of israel': 'israel',
    'state of kuwait': 'kuwait',
    'state of qatar': 'qatar',
    'stp': 'sao tome and principe',
    'sultanate of oman': 'oman',
    'sv': 'el salvador',
    'swiss confederation': 'switzerland',
    'switzerland': 'switzerland',
    'sy': 'syria',
    'syr': 'syria',
    'syria': 'syria',
    'syrian arab republic': 'syria',
    'tajikistan': 'tajikistan',
    'tcd': 'chad',
    'td': 'chad',
    'the state of palestine': 'palestine',
    'the united states': 'united states of america',
    'timor leste': 'timor leste',
    'tj': 'tajikistan',
    'tjk': 'tajikistan',
    'tkm': 'turkmenistan',
    'tl': 'timor leste',
    'tls': 'timor leste',
    'tm': 'turkmenistan',
    'tn': 'tunisia',
    'tr': 'turkey',
    'tun': 'tunisia',
    'tunisia': 'tunisia',
    'tur': 'turkey',
    'turkey': 'turkey',
    'turkiye': 'turkey',
    'turkmenistan': 'turkmenistan',
    'u k': 'united kingdom',
    'u s a': 'united states of america',
    'ua': 'ukraine',
    'uae': 'united arab emirates',
    'uk': 'united kingdom',
    'ukr': 'ukraine',
    'ukraine': 'ukraine',
    'united arab emirates': 'united arab emirates',
    'united kingdom': 'united kingdom',
    'united kingdom of great britain and northern ireland': 'united kingdom',
    'united mexican states': 'mexico',
    'united states': 'united states of america',
    'united states of america': 'united states of america',
    'uruguay': 'uruguay',
    'ury': 'uruguay',
    'us': 'united states of america',
    'usa': 'united states of america',
    'uy': 'uruguay',
    'uz': 'uzbekistan',
    'uzb': 'uzbekistan',
    'uzbekistan': 'uzbekistan',
}


def canon(value: str) -> str:
    """Normalize a country string: strip accents/punctuation, lowercase, collapse spaces."""
    s = unicodedata.normalize("NFKD", str(value))
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = re.sub(r"[^a-z0-9]+", " ", s.lower())
    return re.sub(r"\s+", " ", s).strip()


def resolve(value: str) -> str:
    """Resolve any country form to its canonical key (falls back to canon())."""
    c = canon(value)
    return _ALIAS_TO_CANONICAL.get(c, c)


def article_countries(article: dict) -> list[str]:
    """Extract an article's country value(s) from any of the likely field names.

    Accepts a single string or a list under ``country``/``countries``/
    ``sourceCountry``/``origin``/``geo``. Returns canonical keys (deduped).
    """
    raw = None
    for key in ("countries", "country", "countryName", "sourceCountry", "sourceCountries", "origin", "geo"):
        if key in article and article[key]:
            raw = article[key]
            break
    if raw is None:
        return []
    values = raw if isinstance(raw, (list, tuple, set)) else [raw]
    out: list[str] = []
    for v in values:
        if not v:
            continue
        key = resolve(v)
        if key and key not in out:
            out.append(key)
    return out


def edition_country_keys(source_countries: list[str] | None) -> set[str]:
    """Canonical key set for an edition's declared sourceCountries."""
    return {resolve(c) for c in (source_countries or []) if c}


def matches_edition(article: dict, source_countries: list[str] | None) -> tuple[bool, str | None]:
    """Return (matched, matched_country_key) for an article against an edition.

    If the edition declares no countries, everything matches (returns (True, None)).
    If the article carries no country tag, it does NOT match a country-scoped
    edition (returns (False, None)) - callers decide how to treat untagged stories.
    """
    wanted = edition_country_keys(source_countries)
    if not wanted:
        return True, None
    for key in article_countries(article):
        if key in wanted:
            return True, key
    return False, None